name: Py

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Python
      uses: actions/setup-python@v2.2.1   
         
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v2
      
    - name: Run
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        FCKEY: ${{ secrets.FCKEY }}

      run: python main.py
